org.gradle.jvmargs=-Xmx1536m -XX:+UseSerialGC -XX:MaxMetaspaceSize=384m -Dfile.encoding=UTF-8 -Djdk.net.unixdomain.tmpdir=C:\\st -Djava.net.preferIPv4Stack=true
org.gradle.workers.max=1
kotlin.daemon.jvmargs=-Xmx640m -XX:+UseSerialGC
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
